### ISSUE TITLE
fail to reproduce experimental results

### ISSUE THREAD

**Issue by cs-wangchong** [JohnnyPeng18/TypeGen#1]
After downloading the released data, I executed the following command to reproduce the results of ablation study (RQ3):
```shell
python typegen/evaluate.py -s data/predictions/typegen.json -t data/testset_transformed.json
```
However, the obtained top-5 accuracy (81.0%) was significantly lower than the result reported in the paper (87.5%). 

I also tried "w/o COT Prompt" by running the following command:
```shell
python typegen/evaluate.py -s data/predictions/typegen_no_cot.json -t data/testset_transformed.json
```
Surprisingly, I got a higher top-5 accuracy (82.1%) than what was reported for the complete-version TYPEGEN.

How to correctly reproduce the results?

**Comment by JohnnyPeng18** [comment]
Hi! Thanks very much for your interest! Your problem is due to the incorrect usage of the evaluation script. When evaluating the predictions of TypeGen, you need to add the options `-m` and `-c` to indicate that the predictions are sampled (the common generation method of ChatGPT) and contain Chain-of-Thought prompts. If you want to evaluate the performance of TypeGen without COT prompts, you should remove the option `-c` and just use `-m`.

We have updated the README to avoid confusion.

**Comment by cs-wangchong** [comment]
Thank you very much!
